#!/bin/sh
# Copyright © 2007       Kees Cook <kees@outflux.net>
# Copyright © 2007-2013  Roger Leigh <rleigh@codelibre.net>
#
# schroot is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# schroot is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see
# <http://www.gnu.org/licenses/>.
#
#####################################################################

set -e

. "$SETUP_DATA_DIR/common-data"
. "$SETUP_DATA_DIR/common-functions"
. "$SETUP_DATA_DIR/common-config"

# Wrapper around kill command. Turns errors into
# warnings when running in verbose mode, otherwise
# it ignores them.
# args: parameters for kill
kill_proc()
{
    if ! kill "$@" 2>/dev/null; then
        info "kill $@ failed: process already terminated?"
    fi
}

# Kill all processes that were run from within the chroot environment
# $1: mount base location
do_kill_all()
{
    if [ -z "$1" ]; then
        fatal "No path for finding stray processes: not reaping processes in chroot"
    fi

    chrootpath=$1

    info "Killing processes run inside $chrootpath"

    # pids of running procs will be added to a string 'killproclist' (bash with arrays not always available)
    # format: (string) "pid==executable pid==executable [...]"
    killproclist=""

    # first, send SIGTERM to all running processes
    for pid in $(ls /proc | egrep '^[[:digit:]]+$'); do
        # Check if process root are the same device/inode as chroot
        # root (for efficiency)
        if [ -e /proc/"$pid"/root ] && [ /proc/"$pid"/root -ef "$chrootpath" ]; then
            # Check if process and chroot root are the same (may be
            # different even if device/inode match).
            root=$(readlink /proc/"$pid"/root || true)

            if [ "$root" = "$chrootpath" ]; then
                exe=$(readlink /proc/"$pid"/exe || true)
                exe_short=${exe##$chrootpath}

                # appending those processes to string
                killproclist="$killproclist $pid==$exe_short"

                info  "Killing left-over pid $pid (${exe_short})"
                info  "  Sending SIGTERM to pid $pid"

                kill_proc -TERM "$pid"
            fi
        fi
    done

    # check for process termination in a loop, send SIGKILL afterwards
    # get elements out of string, separated by space.
    for pidexe in $killproclist; do
        pid=${pidexe%%==*} # delete longest match of ==* from back of $pidexe
        exe=${pidexe##*==} # delete longest match of *== from front of $pidexe
        count=0
        max=10
        while [ -d /proc/"$pid" ]; do
            count=$(( $count + 1 ))
            info "  Waiting for pid $pid to shut down... ($count/$max)"
            sleep 0.5
            # Wait for $max halfseconds for process to die before -9'ing it
            if [ "$count" -eq "$max" ]; then
                info "  Sending SIGKILL to pid $pid"
                kill_proc -KILL "$pid"
                sleep 0.5
                break
            fi
        done

        if [ ! -d /proc/"$pid" ]; then
            info "Process '$exe' ($pid) terminated."
        else
            fatal "Process '$exe' ($pid) NOT terminated."
        fi
    done

    info "Finished killing processes run inside $chrootpath"
}

if [ $STAGE = "setup-recover" ] || [ $STAGE = "setup-stop" ]; then
    do_kill_all "$CHROOT_PATH"
fi
